# Generated by Django 5.2.7 on 2025-10-16 07:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyIngredientsLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ingredients_summary', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_limits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Ingredients Limit',
                'verbose_name_plural': 'Daily Ingredients Limits',
                'db_table': 'daily_ingredients_limits',
                'indexes': [models.Index(fields=['user_id'], name='daily_ingre_user_id_84362a_idx'), models.Index(fields=['created_at'], name='daily_ingre_created_5c74a5_idx')],
            },
        ),
    ]
