# Generated by Django 5.2.7 on 2025-10-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='goal',
            field=models.CharField(blank=True, choices=[('lose_weight', 'Lose Weight'), ('gain_weight', 'Gain Weight'), ('maintain_weight', 'Maintain Weight')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='activeness_level',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentary'), ('lightly_active', 'Lightly Active'), ('moderately_active', 'Moderately Active'), ('very_active', 'Very Active'), ('extremely_active', 'Extremely Active')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='motivation',
            field=models.CharField(blank=True, choices=[('vocation', 'Vocation'), ('wedding', 'Wedding'), ('competetion', 'Competetion'), ('other', 'Other'), ('no', 'No')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_diet',
            field=models.CharField(blank=True, choices=[('artificial_intelligence', 'Artificial Intelligence'), ('balanced', 'Balanced'), ('low_carbs', 'Low Carbs'), ('keto', 'Keto'), ('high_protein', 'High Protein'), ('low_fat', 'Low Fat')], max_length=50, null=True),
        ),
    ]
