# Generated by Django 5.2.7 on 2025-10-10 05:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['-meal_date', '-created_at']},
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='image',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
