# Generated by Django 5.2.7 on 2025-10-13 12:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Auto-generated conversation title', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], help_text='Who sent this message: user or ai', max_length=10)),
                ('message', models.TextField(help_text='The actual message content')),
                ('user_id', models.IntegerField(help_text='User ID from the existing system')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('input_tokens', models.IntegerField(default=0, help_text='Tokens in request')),
                ('output_tokens', models.IntegerField(default=0, help_text='Tokens in response')),
                ('total_tokens', models.IntegerField(default=0, help_text='Total tokens used')),
                ('response_time_ms', models.IntegerField(default=0, help_text='AI response time in milliseconds')),
                ('model_used', models.CharField(blank=True, default='', help_text='AI model used', max_length=50)),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.session')),
            ],
            options={
                'db_table': 'message',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='message_session_7ae7d4_idx'), models.Index(fields=['user_id'], name='message_user_id_1e4def_idx'), models.Index(fields=['created_at'], name='message_created_19da1c_idx')],
            },
        ),
    ]
