# Generated by Django 5.2.7 on 2025-10-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietologists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietologist',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
