# Generated by Django 5.2.7 on 2025-10-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietologists', '0002_dietologist_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietologist',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
